<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- The functional tests can't be run in parallel because they conflict with each other when creating docker containers. -->
    <TestTfmsInParallel>false</TestTfmsInParallel>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\HealthChecks.OpenSearch\HealthChecks.OpenSearch.csproj" />
    <PackageReference Include="Testcontainers" />
  </ItemGroup>

</Project>
