<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(ExtendedLibraryTargetFrameworks)</TargetFrameworks>
    <PackageTags>$(PackageTags);Valkey;Redis</PackageTags>
    <Description>HealthChecks.Valkey is the health check package for Valkey connectivity and lightweight command checks.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>

</Project>

