// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.Extensions.DependencyInjection;

namespace HealthChecks.UI.SonnetDB.Storage.Migrations
{
    [DbContext(typeof(SonnetDBHealthChecksDb))]
    partial class HealthChecksDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("HealthChecks.UI.Data.HealthCheckConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INT");

                    b.Property<string>("DiscoveryService")
                        .HasColumnType("STRING")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("STRING")
                        .HasMaxLength(500);

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("STRING")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("HealthChecks.UI.Data.HealthCheckExecution", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INT");

                    b.Property<string>("DiscoveryService")
                        .HasColumnType("STRING")
                        .HasMaxLength(50);

                    b.Property<DateTime>("LastExecuted")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("STRING")
                        .HasMaxLength(500);

                    b.Property<DateTime>("OnStateFrom")
                        .HasColumnType("DATETIME");

                    b.Property<int>("Status")
                        .HasColumnType("INT");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("STRING")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Executions");
                });

            modelBuilder.Entity("HealthChecks.UI.Data.HealthCheckExecutionEntry", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INT");

                    b.Property<string>("Description")
                        .HasColumnType("STRING");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("STRING");

                    b.Property<int?>("HealthCheckExecutionId")
                        .HasColumnType("INT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("STRING")
                        .HasMaxLength(500);

                    b.Property<int>("Status")
                        .HasColumnType("INT");

                    b.Property<string>("Tags")
                        .HasColumnType("STRING");

                    b.HasKey("Id");

                    b.HasIndex("HealthCheckExecutionId");

                    b.ToTable("HealthCheckExecutionEntries");
                });

            modelBuilder.Entity("HealthChecks.UI.Data.HealthCheckExecutionHistory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INT");

                    b.Property<string>("Description")
                        .HasColumnType("STRING");

                    b.Property<int?>("HealthCheckExecutionId")
                        .HasColumnType("INT");

                    b.Property<string>("Name")
                        .HasColumnType("STRING")
                        .HasMaxLength(500);

                    b.Property<DateTime>("On")
                        .HasColumnType("DATETIME");

                    b.Property<int>("Status")
                        .HasColumnType("INT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("HealthCheckExecutionId");

                    b.ToTable("HealthCheckExecutionHistories");
                });

            modelBuilder.Entity("HealthChecks.UI.Data.HealthCheckFailureNotification", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INT");

                    b.Property<string>("HealthCheckName")
                        .IsRequired()
                        .HasColumnType("STRING")
                        .HasMaxLength(500);

                    b.Property<bool>("IsUpAndRunning")
                        .HasColumnType("BOOL");

                    b.Property<DateTime>("LastNotified")
                        .HasColumnType("DATETIME");

                    b.HasKey("Id");

                    b.ToTable("Failures");
                });

            modelBuilder.Entity("HealthChecks.UI.Data.HealthCheckExecutionEntry", b =>
                {
                    b.HasOne("HealthChecks.UI.Data.HealthCheckExecution", null)
                        .WithMany("Entries")
                        .HasForeignKey("HealthCheckExecutionId");
                });

            modelBuilder.Entity("HealthChecks.UI.Data.HealthCheckExecutionHistory", b =>
                {
                    b.HasOne("HealthChecks.UI.Data.HealthCheckExecution", null)
                        .WithMany("History")
                        .HasForeignKey("HealthCheckExecutionId");
                });
#pragma warning restore 612, 618
        }
    }
}
