<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>$(DefaultNetCoreTargetFrameworks)</TargetFrameworks>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
    <NoWarn>$(NoWarn);RCS1090</NoWarn>
    <SignAssembly>false</SignAssembly>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="HealthChecks.UI.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="KubernetesClient" VersionOverride="19.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Sinks.ColoredConsole" />
  </ItemGroup>

</Project>
