name: Legacy HealthChecks EventStore.gRPC CD

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.EventStore.gRPC/HealthChecks.EventStore.gRPC.csproj
      PACKAGE_NAME: NetDiag.HealthChecks.EventStore.gRPC
