name: Legacy HealthChecks AzureServiceBus DB CD

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.AzureServiceBus/HealthChecks.AzureServiceBus.csproj
