name: Legacy HealthChecks Publisher.Seq CD

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.Publisher.Seq/HealthChecks.Publisher.Seq.csproj
      PACKAGE_NAME: NetDiag.HealthChecks.Publisher.Seq
