name: Legacy HealthChecks AzureSearch CD

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.AzureSearch/HealthChecks.AzureSearch.csproj
      PACKAGE_NAME: NetDiag.HealthChecks.AzureSearch
