name: Legacy HealthChecks Aws.SecretsManager CD

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.Aws.SecretsManager/HealthChecks.Aws.SecretsManager.csproj
      PACKAGE_NAME: NetDiag.HealthChecks.Aws.SecretsManager
