name: HealthChecks Aws.SecretsManager CI

permissions:
  contents: read
  packages: write


on:
  workflow_dispatch:
  push:
   branches: [ master ]
   paths:
     - src/HealthChecks.Aws.SecretsManager/**
     - test/HealthChecks.Aws.SecretsManager.Tests/**
     - test/_SHARED/**
     - .github/workflows/healthchecks_aws_secretsmanager_ci.yml
     - .github/workflows/reusable_ci_workflow.yml
     - Directory.Build.props
     - Directory.Build.targets
   tags:
     - v*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.Aws.SecretsManager/**
      - test/HealthChecks.Aws.SecretsManager.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_aws_secretsmanager_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
      - Directory.Packages.props

jobs:
  build:
    uses: ./.github/workflows/reusable_ci_workflow.yml
    secrets: inherit
    with:
      PROJECT_PATH: ./src/HealthChecks.Aws.SecretsManager/HealthChecks.Aws.SecretsManager.csproj
      TEST_PROJECT_PATH: ./test/HealthChecks.Aws.SecretsManager.Tests/HealthChecks.Aws.SecretsManager.Tests.csproj
      CODECOV_FLAGS: Aws.SecretsManager
