name: Legacy HealthChecks IbmMQ Preview CD

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_preview_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      VERSION_SUFFIX_PREFIX: rc1
      PROJECT_PATH: ./src/HealthChecks.IbmMQ/HealthChecks.IbmMQ.csproj
      PACKAGE_NAME: NetDiag.HealthChecks.IbmMQ
