name: Legacy HealthChecks Aws Sns CD

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.Aws.Sns/HealthChecks.Aws.Sns.csproj
      PACKAGE_NAME: NetDiag.HealthChecks.Aws.Sns
